name: Two-Way Cross-Account Sync

on:
  push:
    branches:
      - main  # Change to master if that is your branch name
jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sync Primary to Secondary
        if: github.repository == 'shlokdobriyal/esy'
        env:
          SECONDARY_REPO: "://github.com"
          SECONDARY_PAT: ${{ secrets.SECONDARY_ACCOUNT_PAT }}
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "sync-bot@example.com"
          git remote add target https://x-access-token:${SECONDARY_PAT}@${SECONDARY_REPO} 2>/dev/null || git remote set-url target https://x-access-token:${SECONDARY_PAT}@${SECONDARY_REPO}
          git fetch target main
          git merge target/main --no-edit
          git push target main
          git merge target/main --no-edit
          git push target main

      # RUN THIS PART ONLY IF WE ARE ON THE SECONDARY ACCOUNT
       if: github.repository == 'ishuD26/esy'
      - name: Sync Secondary to Primary
        env:
          PRIMARY_REPO: "://github.com"
          PRIMARY_PAT: ${{ secrets.PRIMARY_ACCOUNT_PAT }}
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "sync-bot@example.com"
          git remote add target https://x-access-token:${PRIMARY_PAT}@${PRIMARY_REPO}
          git fetch target main
          git merge target/main --no-edit
          git push target main
